### ISSUE TITLE
Відсутність повідомлення про додавання відгуку

### ISSUE THREAD

**Issue by victorialysenko** [appl-dpt/HospitalSeeker#4]
При спробі додати відгук, пацієнт не має можливость побачити щойно написаний відгук. Також при написанні відгуку без натискання кнопки "Submit" пропадає можливість повторного написання відгуку.
Кроки для відтворення:
1. Зайти на сторінку лікаря
2. Написати відгук
3. Натиснути "Submit" 
Очікуваний результат: з'явиться повідомлення про успішне написання повідомлення.
Реальний результат: кнопка "Submit" стає disabled і зникає поле для відгуку.

**Comment by appl-dpt** [comment]
Deleted
